import React, { useState } from 'react';
import { Search, Bell, Settings, ArrowRight, User } from 'lucide-react';

export default function AIDesignedDashboard() {
  const [activeTab, setActiveTab] = useState('overview');
  const [showNotifications, setShowNotifications] = useState(false);

  return (
    <div className="min-h-screen bg-slate-950 text-slate-50 font-sans p-6">
      {/* Header Panel */}
      <header className="flex justify-between items-center bg-slate-900 border border-slate-800 p-4 rounded-xl mb-8">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg bg-gradient-to-tr from-indigo-500 to-purple-500 flex items-center justify-center font-bold text-lg text-white">
            AI
          </div>
          <div>
            <h1 className="text-md font-semibold leading-none">Developer Portal</h1>
            <p className="text-xs text-slate-400 mt-1">Generated by v0.dev AI</p>
          </div>
        </div>

        {/* Search Bar Input */}
        <div className="flex items-center bg-slate-950 border border-slate-800 rounded-lg px-3 py-1.5 w-64 gap-2">
          <Search className="w-4 h-4 text-slate-400" />
          {/* ⚠️ VIOLATION: Input missing label or aria-label */}
          <input 
            type="text" 
            placeholder="Search projects..." 
            className="bg-transparent border-none text-sm outline-none text-slate-100 placeholder-slate-500 w-full" aria-label="Search projects..."/>
        </div>

        <div className="flex items-center gap-4">
          {/* ⚠️ VIOLATION: Interactive Div used for Notifications (no role="button", no tabIndex, no keyboard trigger) */}
          <div 
            onClick={() => setShowNotifications(!showNotifications)}
            className="cursor-pointer p-2 rounded-lg bg-slate-950 hover:bg-slate-800 border border-slate-800 transition text-slate-300 hover:text-white"
          >
            <Bell className="w-4 h-4" />
          </div>

          {/* ⚠️ VIOLATION: SVG Button with no labels or text context */}
          <button className="p-2 rounded-lg bg-slate-950 hover:bg-slate-800 border border-slate-800 transition" aria-label="Settings">
            <Settings className="w-4 h-4 text-slate-300" />
          </button>

          <div className="flex items-center gap-2 bg-slate-950 px-3 py-1.5 rounded-lg border border-slate-800 cursor-pointer" role="button" tabIndex={0} onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); e.currentTarget.click(); } }}>
            <div className="w-6 h-6 rounded-full bg-slate-800 flex items-center justify-center text-xs">
              <User className="w-3.5 h-3.5" />
            </div>
            <span className="text-xs font-medium">Sarah Jenkins</span>
          </div>
        </div>
      </header>

      {/* Main Board */}
      <main className="grid grid-cols-1 md:grid-cols-3 gap-6">
        
        {/* Project Card */}
        <div className="md:col-span-2 bg-slate-900 border border-slate-800 rounded-xl p-6 flex flex-col justify-between h-64 shadow-xl">
          <div>
            <span className="text-xs font-semibold text-indigo-400 uppercase tracking-wider">Active Deployments</span>
            <h2 className="text-2xl font-bold mt-2">Next.js Cloud Workspace</h2>
            <p className="text-sm text-slate-400 mt-2 leading-relaxed">
              Real-time synchronization with active GitHub runner nodes. Deploying styled Tailwind bundles dynamically.
            </p>
          </div>

          <div className="flex justify-between items-center border-t border-slate-800 pt-4 mt-6">
            <span className="text-xs text-slate-400">Audited 12 mins ago</span>
            
            {/* ⚠️ VIOLATION: Custom click-handler Div without keyboard support */}
            <div 
              onClick={() => alert("Redirecting to active workspace pipeline...")}
              className="flex items-center gap-1.5 text-xs text-indigo-400 hover:text-indigo-300 cursor-pointer font-semibold"
            >
              Configure Actions <ArrowRight className="w-3.5 h-3.5" />
            </div>
          </div>
        </div>

        {/* Sidebar Preview Illustrative Card */}
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 flex flex-col justify-between shadow-xl">
          <div>
            <span className="text-xs font-semibold text-purple-400 uppercase tracking-wider">AI Asset Preview</span>
            
            {/* ⚠️ VIOLATION: Illustrative Image without alt text descriptor */}
            <img 
              src="https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=400" 
              className="w-full rounded-lg border border-slate-800 object-cover h-32 mt-4" alt="A cat looks at a laptop which displays an illustration of a robot."/>
          </div>

          <div className="mt-4 flex items-center justify-between text-xs text-slate-400">
            <span>Visual mockup assets</span>
            <span className="text-purple-400 font-bold">Unlabelled</span>
          </div>
        </div>

      </main>
    </div>
  );
}
