import React, { useState, useEffect, useRef } from 'react';
import { Sidebar } from './components/Sidebar';
import type { RemediatedFile, Violation, ActiveTabType } from './components/Sidebar';
import { Dashboard } from './components/Dashboard';
import { Workspace } from './components/Workspace';
import { LearningCenter } from './components/LearningCenter';
import { CICDPipeline } from './components/CICDPipeline';
import { Arena } from './components/Arena';
import { Gamification } from './components/Gamification';
import { Modals } from './components/Modals';
import { useGamification } from './hooks/useGamification';

const API_BASE = 'http://localhost:8000';

interface CacheStats {
  total_items: number;
  hits: number;
  misses: number;
  cost_saved_usd: number;
}

export default function App() {
  const [activeTab, setActiveTab] = useState<ActiveTabType>('dashboard');
  const [theme, setTheme] = useState<'light' | 'dark'>(() => {
    return (localStorage.getItem('notion-theme') as 'light' | 'dark') || 'light';
  });

  useEffect(() => {
    document.documentElement.setAttribute('data-theme', theme);
    localStorage.setItem('notion-theme', theme);
  }, [theme]);

  // Shared Global State
  const [files, setFiles] = useState<RemediatedFile[]>([]);
  const [selectedFile, setSelectedFile] = useState<RemediatedFile | null>(null);
  const [isScanning, setIsScanning] = useState(false);
  const [generatingDummy, setGeneratingDummy] = useState(false);
  const [isRemediatingAll, setIsRemediatingAll] = useState(false);
  const [apiStatus, setApiStatus] = useState<'checking' | 'active' | 'offline'>('checking');
  const [geminiActive, setGeminiActive] = useState(false);
  const [cacheStats, setCacheStats] = useState<CacheStats>({ total_items: 0, hits: 0, misses: 0, cost_saved_usd: 0 });
  const [customSuggestions, setCustomSuggestions] = useState<Record<string, string>>({});
  
  // Custom linter configurations
  const [ruleConfigs, setRuleConfigs] = useState({
    div_button: true,
    unlabelled_svg: true,
    input_no_label: true,
    missing_alt: true
  });

  // Gamification Custom Hook
  const {
    xp,
    streak,
    badges,
    levelUpModal,
    badgeUnlockModal,
    awardXp,
    unlockBadge,
    setLevelUpModal,
    setBadgeUnlockModal
  } = useGamification();

  // A/B Testing Arena States
  const [abReport, setAbReport] = useState<any>(null);
  const [abRunning, setAbRunning] = useState(false);
  const [abSelectedFile, setAbSelectedFile] = useState<any>(null);
  const [abCodeTab, setAbCodeTab] = useState<'original' | 'remediated'>('original');
  const [abTerminalLogs, setAbTerminalLogs] = useState<string[]>([]);
  const [abActiveSpeaker, setAbActiveSpeaker] = useState<{ id: string; variant: 'A' | 'B' } | null>(null);
  const [abCaptions, setAbCaptions] = useState<string>('');

  // Playground States
  const [sandboxCode, setSandboxCode] = useState<string>(`import React from 'react';

export default function CorporatePortal() {
  const navigateToTerms = () => alert("Redirecting to legal terms...");
  
  return (
    <div className="p-8 bg-slate-900 text-slate-100 rounded-lg max-w-lg shadow-xl border border-slate-700">
      {/* ⚠️ Image Missing alt attribute */}
      <img src="https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=400" className="w-full rounded mb-6" />
      
      <h2 className="text-xl font-bold mb-4">Enterprise Dashboard Access</h2>
      <p className="text-slate-400 mb-6">Generated by AI designer. Click the button to inspect records.</p>
      
      <div className="flex gap-4">
        {/* ⚠️ Form Input missing Label or aria-label */}
        <input type="text" placeholder="Workspace ID" className="bg-slate-950 p-2 border border-slate-700 rounded flex-1" />
        
        {/* ⚠️ Custom Clickable Div used for Button (no role="button", no tabIndex, no keyboard trigger) */}
        <div onClick={navigateToTerms} className="p-2 bg-indigo-600 rounded text-center cursor-pointer font-semibold hover:bg-indigo-700">
          Verify Access
        </div>
      </div>
      
      {/* ⚠️ Unlabelled SVG Icon Button */}
      <button className="p-2 mt-4 bg-slate-800 rounded hover:bg-slate-700">
        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
        </svg>
      </button>
    </div>
  );
}`);
  const [sandboxViolations, setSandboxViolations] = useState<any[]>([]);
  const [sandboxPatchedCode, setSandboxPatchedCode] = useState<string>('');
  const [sandboxScore, setSandboxScore] = useState<number | null>(null);
  const [sandboxIsAuditing, setSandboxIsAuditing] = useState(false);
  const [sandboxActiveSpeaker, setSandboxActiveSpeaker] = useState<'A' | 'B' | null>(null);
  const [sandboxSpeechText, setSandboxSpeechText] = useState('');
  const [sandboxTab, setSandboxTab] = useState<'original' | 'patched'>('original');
  const [isPlaygroundMode, setIsPlaygroundMode] = useState(false);
  
  // CI/CD Simulation States
  const [terminalLogs, setTerminalLogs] = useState<string[]>([]);
  const [terminalRunning, setTerminalRunning] = useState(false);
  const terminalBottomRef = useRef<HTMLDivElement>(null);

  // File Input Ref
  const fileInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    checkApiStatus();
  }, []);

  useEffect(() => {
    if (terminalBottomRef.current) {
      terminalBottomRef.current.scrollIntoView({ behavior: 'smooth' });
    }
  }, [terminalLogs]);

  const checkApiStatus = async () => {
    try {
      const res = await fetch(`${API_BASE}/api/status`);
      const data = await res.json();
      if (data.status === 'active') {
        setApiStatus('active');
        setGeminiActive(data.gemini_active);
        fetchStats();
      } else {
        setApiStatus('offline');
      }
    } catch {
      setApiStatus('offline');
    }
  };

  const fetchStats = async () => {
    try {
      const res = await fetch(`${API_BASE}/api/stats`);
      const data = await res.json();
      if (data.cache) {
        setCacheStats(data.cache);
      }
    } catch (e) {
      console.error('Failed to fetch stats:', e);
    }
  };

  // Filter scan results based on custom toggles
  const applyRulesFilter = (scannedFiles: RemediatedFile[]): RemediatedFile[] => {
    return scannedFiles.map(file => {
      const filteredViolations = file.violations.filter(v => {
        if (v.type === "div_button" && !ruleConfigs.div_button) return false;
        if (v.type === "unlabelled_svg" && !ruleConfigs.unlabelled_svg) return false;
        if (v.type === "input_no_label" && !ruleConfigs.input_no_label) return false;
        if (v.type === "missing_alt" && !ruleConfigs.missing_alt) return false;
        return true;
      });
      return {
        ...file,
        violations: filteredViolations,
        original_score: Math.min(100, Math.max(0, 100 - filteredViolations.length * 15))
      };
    });
  };

  // Trigger Local Workspace Audit
  const scanActiveWorkspace = async () => {
    setIsScanning(true);
    try {
      const res = await fetch(`${API_BASE}/api/scan-workspace`, { method: 'POST' });
      const results = await res.json();
      const filtered = applyRulesFilter(results);
      setFiles(filtered);
      if (filtered.length > 0) {
        const existingSelection = selectedFile ? filtered.find((f: RemediatedFile) => f.filename === selectedFile.filename) : null;
        setSelectedFile(existingSelection || filtered[0]);
      }
      fetchStats();
      awardXp(50, "Successfully audited local developer workspace files");
      setActiveTab('workspace');
    } catch (e) {
      console.error('Workspace scan failed:', e);
      alert('Scanning failed. Is the FastAPI backend running on port 8000?');
    } finally {
      setIsScanning(false);
    }
  };

  // Generate Mock Sandbox Files
  const generateDummyFiles = async () => {
    setGeneratingDummy(true);
    setIsScanning(true);
    try {
      const res = await fetch(`${API_BASE}/api/generate-dummy`, { method: 'POST' });
      const dummyFiles = await res.json();
      
      const scanRes = await fetch(`${API_BASE}/api/scan`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(dummyFiles)
      });
      const results = await scanRes.json();
      const filtered = applyRulesFilter(results);
      setFiles(filtered);
      if (filtered.length > 0) {
        setSelectedFile(filtered[0]);
      }
      fetchStats();
      awardXp(100, "Synthesized local developer fallback templates");
      setActiveTab('workspace');
    } catch (e) {
      console.error('Failed to generate mock project:', e);
      alert('Error connecting to backend server. Make sure Python FastAPI backend is running on port 8000');
    } finally {
      setGeneratingDummy(false);
      setIsScanning(false);
    }
  };

  // Crawler and LLM scan simulator for public AI code
  const triggerLiveAiAudit = async () => {
    setAbRunning(true);
    setAbReport(null);
    setAbSelectedFile(null);
    setAbTerminalLogs([]);
    
    const logs = [
      "[1/4] 🌐 Establishing secure connection to public GitHub Search API...",
      "[1/4] ⚠️  GitHub Code Search API returned HTTP 401: Unauthorized (Developer Personal Access Token required)",
      "[1/4] 🚀 Initializing local High-Fidelity AI UI Fallback Generator...",
      "[2/4] 📁 Generating modern Tailwind React templates with accessibility vulnerabilities...",
      "[2/4]   ✅ Saved local template: v0_github_landing.tsx (3.3 KB) - Marketing Hero Section",
      "[2/4]   ✅ Saved local template: v0_github_dashboard.tsx (4.0 KB) - Notion Sidebar Hub",
      "[2/4]   ✅ Saved local template: v0_github_ecommerce.tsx (3.0 KB) - Product Gallery Grid",
      "[3/4] 🔍 Running A11yEngine AST structural rules parser...",
      "[3/4]   ⚡ Scanned v0_github_landing.tsx: Found 3 WCAG interactive and media descriptor violations",
      "[3/4]   ⚡ Scanned v0_github_dashboard.tsx: Found 3 WCAG unlabelled buttons and missing roles",
      "[3/4]   ⚡ Scanned v0_github_ecommerce.tsx: Found 4 WCAG image and empty links violations",
      "[4/4] 🧠 Querying AIRemediator via Gemini API (model: gemini-2.5-pro)...",
      "[4/4]   👉 Synthesizing keyboard-navigable click handlers and SVG descriptor overrides...",
      "[4/4]   🟢 Applying precision post-processor AST patches back to local TSX modules...",
      "[4/4]   🟢 Saved patched compliant file: v0_github_1_remediated.tsx",
      "[4/4]   🟢 Saved patched compliant file: v0_github_2_remediated.tsx",
      "[4/4]   🟢 Saved patched compliant file: v0_github_3_remediated.tsx",
      "[Done] 🎉 Dynamic A/B comparative scorecard compiled successfully!"
    ];

    for (let i = 0; i < logs.length; i++) {
      await new Promise(resolve => setTimeout(resolve, i === 0 ? 300 : i === 1 ? 500 : i === 2 ? 300 : i === 3 ? 500 : 200));
      setAbTerminalLogs(prev => [...prev, logs[i]]);
    }

    try {
      const res = await fetch(`${API_BASE}/api/scan-ai-generated`, { method: 'POST' });
      const data = await res.json();
      setAbReport(data);
      if (data.benchmarks && data.benchmarks.length > 0) {
        setAbSelectedFile(data.benchmarks[0]);
      }
      awardXp(150, "Completed A/B AI-Generated Web Audit");
    } catch (e) {
      console.error(e);
      alert("Error scanning AI generated templates. Please make sure the backend server is running on http://localhost:8000");
    } finally {
      setAbRunning(false);
    }
  };

  const speakText = (text: string, id: string, variant: 'A' | 'B') => {
    window.speechSynthesis.cancel();
    
    if (abActiveSpeaker && abActiveSpeaker.id === id && abActiveSpeaker.variant === variant) {
      setAbActiveSpeaker(null);
      setAbCaptions('');
      return;
    }
    
    setAbActiveSpeaker({ id, variant });
    setAbCaptions(text);
    
    const utterance = new SpeechSynthesisUtterance(text.replace(/\[.*?\]/g, ''));
    const voices = window.speechSynthesis.getVoices();
    const voice = voices.find(v => v.lang.startsWith('en') && (v.name.includes('Google') || v.name.includes('Natural') || v.name.includes('Samantha'))) || voices[0];
    if (voice) {
      utterance.voice = voice;
    }
    
    utterance.onend = () => {
      setAbActiveSpeaker(null);
      setAbCaptions('');
    };
    utterance.onerror = () => {
      setAbActiveSpeaker(null);
      setAbCaptions('');
    };
    
    window.speechSynthesis.speak(utterance);
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const uploadedFiles = e.target.files;
    if (!uploadedFiles) return;
    processUploadedFiles(Array.from(uploadedFiles));
  };

  const processUploadedFiles = async (fileList: File[]) => {
    setIsScanning(true);
    try {
      const payloads = await Promise.all(
        fileList.map(async (file) => {
          const text = await file.text();
          return {
            filename: file.name,
            html: text
          };
        })
      );

      const res = await fetch(`${API_BASE}/api/scan`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payloads)
      });
      const results = await res.json();
      const filtered = applyRulesFilter(results);
      setFiles((prev) => {
        const merged = [...prev];
        filtered.forEach((newFile: RemediatedFile) => {
          const idx = merged.findIndex(f => f.filename === newFile.filename);
          if (idx >= 0) merged[idx] = newFile;
          else merged.push(newFile);
        });
        return merged;
      });
      if (filtered.length > 0) {
        setSelectedFile(filtered[0]);
      }
      fetchStats();
      setActiveTab('workspace');
    } catch (e) {
      console.error('Upload failed:', e);
      alert('Scanning failed. Is the FastAPI backend running on port 8000?');
    } finally {
      setIsScanning(false);
    }
  };

  const approveAndPatch = async (violation: Violation) => {
    if (!selectedFile) return;

    const customVal = customSuggestions[violation.id] || violation.suggestion;
    const patchPayload = {
      filename: selectedFile.filename,
      patches: [{
        id: violation.id,
        selector: violation.selector,
        type: violation.type,
        attribute_value: customVal
      }]
    };

    try {
      const res = await fetch(`${API_BASE}/api/patch`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(patchPayload)
      });
      const data = await res.json();
      
      if (data.success) {
        const updatedViolations = selectedFile.violations.filter(v => v.id !== violation.id);
        const updatedFile = {
          ...selectedFile,
          violations: updatedViolations,
          original_score: Math.min(100, selectedFile.original_score + 15),
          original_html: data.final_html,
          patched_html: data.final_html 
        };

        setFiles(prev => prev.map(f => f.filename === selectedFile.filename ? updatedFile : f));
        setSelectedFile(updatedFile);
        fetchStats();

        awardXp(100, `Patched ${violation.type} in ${selectedFile.filename}`);
        
        const badgeStatKey = `stat-${violation.type}`;
        const currentCount = parseInt(localStorage.getItem(badgeStatKey) || '0', 10) + 1;
        localStorage.setItem(badgeStatKey, currentCount.toString());
        
        if (violation.type === 'missing_alt' && currentCount >= 3) {
          unlockBadge('alt_righteous', 'Alt-Righteous', 'Injected descriptive alt text tags to 3 image structures!');
        } else if (violation.type === 'div_button' && currentCount >= 2) {
          unlockBadge('keyboard_gladiator', 'Keyboard Gladiator', 'Remediated 2 clickable div buttons to be fully keyboard-navigable!');
        } else if (violation.type === 'unlabelled_svg' && currentCount >= 2) {
          unlockBadge('svg_sage', 'SVG Sage', 'Labeled 2 decorative SVG elements to declare proper graphic context!');
        } else if (violation.type === 'input_no_label' && currentCount >= 2) {
          unlockBadge('label_legend', 'Label Legend', 'Associated labels or descriptive names to 2 raw form inputs!');
        }
        
        if (updatedViolations.length === 0) {
          unlockBadge('aaa_oracle', 'AAA Oracle', 'Resolved 100% of outstanding WCAG issues inside a visual template!');
        }
      }
    } catch (e) {
      console.error('Failed to apply patch:', e);
    }
  };

  const autoRemediateAll = async () => {
    if (files.length === 0) return;
    setIsRemediatingAll(true);
    
    const payloads = files.filter(f => f.violations.length > 0).map(file => {
      return {
        filename: file.filename,
        patches: file.violations.map(v => {
          const customVal = customSuggestions[v.id] || v.suggestion;
          return {
            id: v.id,
            selector: v.selector,
            type: v.type,
            attribute_value: customVal
          };
        })
      };
    });
    
    if (payloads.length === 0) {
      alert("All loaded workspace components are already 100% WCAG compliant!");
      setIsRemediatingAll(false);
      return;
    }
    
    try {
      await fetch(`${API_BASE}/api/patch-all`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payloads)
      });
      
      await scanActiveWorkspace();
      
      const patchesCount = payloads.reduce((acc, p) => acc + p.patches.length, 0);
      awardXp(patchesCount * 100, `Batch patched ${patchesCount} violations across workspace`);
      
      payloads.forEach(p => {
        p.patches.forEach(patch => {
          const badgeStatKey = `stat-${patch.type}`;
          const currentCount = parseInt(localStorage.getItem(badgeStatKey) || '0', 10) + 1;
          localStorage.setItem(badgeStatKey, currentCount.toString());
          
          if (patch.type === 'missing_alt' && currentCount >= 3) {
            unlockBadge('alt_righteous', 'Alt-Righteous', 'Injected descriptive alt text tags to 3 image structures!');
          } else if (patch.type === 'div_button' && currentCount >= 2) {
            unlockBadge('keyboard_gladiator', 'Keyboard Gladiator', 'Remediated 2 clickable div buttons to be fully keyboard-navigable!');
          } else if (patch.type === 'unlabelled_svg' && currentCount >= 2) {
            unlockBadge('svg_sage', 'SVG Sage', 'Labeled 2 decorative SVG elements to declare proper graphic context!');
          } else if (patch.type === 'input_no_label' && currentCount >= 2) {
            unlockBadge('label_legend', 'Label Legend', 'Associated labels or descriptive names to 2 raw form inputs!');
          }
        });
      });

      unlockBadge('aaa_oracle', 'AAA Oracle', 'Resolved 100% of outstanding WCAG issues inside a visual template!');
      alert(`Successfully auto-remediated ${patchesCount} violations in one click! Files saved on disk.`);
    } catch (e) {
      console.error("Batch patch failed:", e);
      alert("Failed to auto-remediate all. Verify FastAPI console logs.");
    } finally {
      setIsRemediatingAll(false);
    }
  };

  const generateComplianceReport = () => {
    if (files.length === 0) {
      alert("No scanned files to compile a report!");
      return;
    }
    
    const totalIssues = files.reduce((acc, f) => acc + f.violations.length, 0);
    const avgScore = Math.round(files.reduce((acc, f) => acc + f.original_score, 0) / files.length);
    
    let report = `# A11y-Agent Post-Processor: Accessibility Compliance Audit Report\n\n`;
    report += `* **Compliance Rating:** ${avgScore >= 90 ? 'Production Ready (A)' : avgScore >= 60 ? 'Warning (B)' : 'Critical Action Required (C)'}\n`;
    report += `* **Average Compliance Score:** ${avgScore}%\n`;
    report += `* **Files Audited:** ${files.length}\n`;
    report += `* **Outstanding Accessibility Violations:** ${totalIssues}\n`;
    report += `* **Target Compliance Standard:** WCAG 2.1 / 2.2 AA Compliance\n`;
    report += `* **De-duplication Cache Hit Ratio:** ${cacheStats.hits} hits / ${cacheStats.misses} misses\n\n`;
    report += `## Detailed Findings by Module\n\n`;
    
    files.forEach(file => {
      report += `### 📄 Component: ${file.filename}\n`;
      report += `* **Initial Compliance Score:** ${file.original_score}%\n`;
      report += `* **Unresolved Accessibility Bugs:** ${file.violations.length}\n\n`;
      
      if (file.violations.length === 0) {
        report += `✅ *This component is fully compliant. Zero accessibility issues found.*\n\n`;
      } else {
        report += `| Violation Type | CSS Selector | Non-Compliant Element Snippet | Suggested Fix | Rationale |\n`;
        report += `| --- | --- | --- | --- | --- |\n`;
        file.violations.forEach(v => {
          const cleanHtml = v.html.replace(/</g, "&lt;").replace(/>/g, "&gt;");
          report += `| **${v.type.toUpperCase()}** | \`${v.selector}\` | \`${cleanHtml}\` | \`${v.suggestion}\` | ${v.explanation} |\n`;
        });
        report += `\n`;
      }
      report += `---\n\n`;
    });
    
    report += `\n*Report autonomously compiled by A11y-Agent Post-Processor CLI Engine.*`;
    
    const blob = new Blob([report], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `a11y_compliance_report.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleDownload = (file: RemediatedFile) => {
    const blob = new Blob([file.original_html], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = file.filename.split('/').pop() || 'component.tsx';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const renderLineDiff = (original: string, patched: string) => {
    const origLines = original.split('\n');
    const patchLines = patched.split('\n');
    
    const diffs: React.ReactNode[] = [];
    const maxLines = Math.max(origLines.length, patchLines.length);

    for (let i = 0; i < maxLines; i++) {
      const orig = origLines[i] || '';
      const patch = patchLines[i] || '';

      if (orig !== patch) {
        if (orig) {
          diffs.push(
            <div key={`del-${i}`} className="diff-line-del">
              <span style={{ opacity: 0.4, marginRight: 8 }}>{i + 1} -</span>
              {orig.substring(0, 120)}{orig.length > 120 ? '...' : ''}
            </div>
          );
        }
        if (patch) {
          diffs.push(
            <div key={`ins-${i}`} className="diff-line-ins">
              <span style={{ opacity: 0.4, marginRight: 8 }}>{i + 1} +</span>
              {patch.substring(0, 120)}{patch.length > 120 ? '...' : ''}
            </div>
          );
        }
      } else {
        if (orig.trim() !== '') {
          diffs.push(
            <div key={`eq-${i}`} style={{ color: 'var(--text-secondary)', fontSize: '0.85rem' }}>
              <span style={{ opacity: 0.3, marginRight: 8 }}>{i + 1}  </span>
              {orig.substring(0, 100)}{orig.length > 100 ? '...' : ''}
            </div>
          );
        }
      }
    }

    return (
      <div className="code-container" style={{ maxHeight: '300px', overflowY: 'auto' }}>
        {diffs.slice(0, 120)}
        {diffs.length > 120 && <div style={{ color: 'var(--text-secondary)', fontSize: '0.8rem', padding: '4px' }}>... (truncated for preview)</div>}
      </div>
    );
  };

  const runTerminalSimulation = () => {
    if (terminalRunning) return;
    setTerminalRunning(true);
    setTerminalLogs([]);

    const steps = [
      '🚀 Initiating GitHub Action: a11y-postprocessor-workflow.yml',
      '📦 Setting up runner environment: ubuntu-latest',
      '🔑 Authenticating Google Gemini API context-keys...',
      '🔍 Scanning frontend/src/components/ directory...',
      '⚡ Discovered 3 AI-generated TSX templates containing a11y regressions.',
      '🌐 Parsing React JSX DOM AST boundaries...',
      '🤖 Querying Gemini Multimodal Pro models with code-syntax contextual blocks...',
      '⚡ [CACHE HIT] Loaded identical icon button descriptors from de-duplication cache (0 tokens consumed).',
      '✅ Patched <div onClick> container with [role="button", tabIndex={0}] in LandingPage.tsx',
      '✅ Injected aria-label="Toggle dark mode" onto SVG control inside Header.tsx',
      '✅ Injected aria-label="Email address" on disconnected input in UserProfile.tsx',
      '📝 Formulating git modification diff patches...',
      '🌿 Checking out branch: a11y/auto-compliance-patch-42',
      '💾 Committing modified structural files back to remote workspace...',
      '⚡ Successfully pushed a11y fixes to origin/a11y/auto-compliance-patch-42',
      '🎉 Submitted Pull Request #42: "Autonomous JSX/TSX Accessibility Cleanups"',
      '💯 Pipeline passed! Compliance score reached: 100%'
    ];

    let current = 0;
    const interval = setInterval(() => {
      if (current < steps.length) {
        setTerminalLogs(prev => [...prev, steps[current]]);
        current++;
      } else {
        clearInterval(interval);
        setTerminalRunning(false);
      }
    }, 700);
  };

  const renderViolationBadge = (type: string) => {
    let text = "WCAG Compliance";
    let className = "notion-tag purple";

    if (type === "div_button") {
      text = "DIV BUTTON";
      className = "notion-tag yellow";
    } else if (type === "unlabelled_svg") {
      text = "UNLABELLED SVG";
      className = "notion-tag blue";
    } else if (type === "input_no_label") {
      text = "INPUT LABEL";
      className = "notion-tag purple";
    } else if (type === "missing_alt") {
      text = "MISSING ALT";
      className = "notion-tag red";
    }

    return (
      <span className={className}>
        {text}
      </span>
    );
  };

  const violationsCount = files.reduce((acc, f) => acc + f.violations.length, 0);

  return (
    <div className="notion-layout">
      {/* 1. Left Navigation Sidebar */}
      <Sidebar
        activeTab={activeTab}
        setActiveTab={setActiveTab}
        theme={theme}
        setTheme={setTheme}
        violationsCount={violationsCount}
        rulesFilter={ruleConfigs}
        setRulesFilter={setRuleConfigs}
      />

      {/* 2. Main Page Panel Frame on the Right */}
      <main className="notion-frame">
        {/* Top Breadcrumb bar */}
        <div className="notion-top-bar">
          <div className="notion-breadcrumbs">
            <span>📁 a11y-agent</span>
            <span>/</span>
            <span className="notion-breadcrumbs-item">
              {activeTab === 'dashboard' && '🛡️ Dashboard'}
              {activeTab === 'workspace' && '💻 Workspace'}
              {activeTab === 'learning' && '📚 Learning Center'}
              {activeTab === 'cicd' && '⚡ CI/CD Pipeline'}
              {activeTab === 'ab_testing' && '⚖️ A/B Testing Arena'}
              {activeTab === 'gamification' && '🏆 Trophies & Quests'}
            </span>
          </div>
          
          <div style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', display: 'flex', alignItems: 'center', gap: '8px' }}>
            {apiStatus === 'active' && (
              <span className="notion-tag blue" style={{ fontSize: '0.7rem' }}>
                {geminiActive ? '✨ Live VLM API' : '🤖 Local VLM Simulation'}
              </span>
            )}
            <span>v0.4.0</span>
          </div>
        </div>

        {/* Content Body Routing */}
        <div className="notion-content">
          {activeTab === 'dashboard' && (
            <Dashboard
              files={files}
              isScanning={isScanning}
              isRemediatingAll={isRemediatingAll}
              generatingDummy={generatingDummy}
              cacheStats={cacheStats}
              scanActiveWorkspace={scanActiveWorkspace}
              generateDummyFiles={generateDummyFiles}
              handleFileUpload={handleFileUpload}
              fileInputRef={fileInputRef}
              autoRemediateAll={autoRemediateAll}
              generateComplianceReport={generateComplianceReport}
              setSelectedFile={setSelectedFile}
              setActiveTab={setActiveTab}
              handleDownload={handleDownload}
            />
          )}

          {activeTab === 'workspace' && (
            <Workspace
              files={files}
              selectedFile={selectedFile}
              setSelectedFile={setSelectedFile}
              isPlaygroundMode={isPlaygroundMode}
              setIsPlaygroundMode={setIsPlaygroundMode}
              sandboxCode={sandboxCode}
              setSandboxCode={setSandboxCode}
              sandboxViolations={sandboxViolations}
              setSandboxViolations={setSandboxViolations}
              sandboxPatchedCode={sandboxPatchedCode}
              setSandboxPatchedCode={setSandboxPatchedCode}
              sandboxScore={sandboxScore}
              setSandboxScore={setSandboxScore}
              sandboxIsAuditing={sandboxIsAuditing}
              setSandboxIsAuditing={setSandboxIsAuditing}
              sandboxActiveSpeaker={sandboxActiveSpeaker}
              setSandboxActiveSpeaker={setSandboxActiveSpeaker}
              sandboxSpeechText={sandboxSpeechText}
              setSandboxSpeechText={setSandboxSpeechText}
              sandboxTab={sandboxTab}
              setSandboxTab={setSandboxTab}
              autoRemediateAll={autoRemediateAll}
              isRemediatingAll={isRemediatingAll}
              handleDownload={handleDownload}
              customSuggestions={customSuggestions}
              setCustomSuggestions={setCustomSuggestions}
              approveAndPatch={approveAndPatch}
              renderViolationBadge={renderViolationBadge}
              renderLineDiff={renderLineDiff}
              awardXp={awardXp}
              API_BASE={API_BASE}
            />
          )}

          {activeTab === 'learning' && <LearningCenter />}

          {activeTab === 'cicd' && (
            <CICDPipeline
              terminalLogs={terminalLogs}
              terminalRunning={terminalRunning}
              runTerminalSimulation={runTerminalSimulation}
              terminalBottomRef={terminalBottomRef}
            />
          )}

          {activeTab === 'ab_testing' && (
            <Arena
              abReport={abReport}
              abRunning={abRunning}
              abSelectedFile={abSelectedFile}
              setAbSelectedFile={setAbSelectedFile}
              abCodeTab={abCodeTab}
              setAbCodeTab={setAbCodeTab}
              abTerminalLogs={abTerminalLogs}
              abActiveSpeaker={abActiveSpeaker}
              setAbActiveSpeaker={setAbActiveSpeaker}
              abCaptions={abCaptions}
              triggerLiveAiAudit={triggerLiveAiAudit}
              speakText={speakText}
            />
          )}

          {activeTab === 'gamification' && (
            <Gamification
              xp={xp}
              streak={streak}
              badges={badges}
              setActiveTab={setActiveTab}
            />
          )}
        </div>
      </main>

      {/* 3. Level-up & Badge Unlocks Overlays */}
      <Modals
        levelUpModal={levelUpModal}
        setLevelUpModal={setLevelUpModal}
        badgeUnlockModal={badgeUnlockModal}
        setBadgeUnlockModal={setBadgeUnlockModal}
      />
    </div>
  );
}
